// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://whaihclwfwpmcvpnkctv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoYWloY2x3ZndwbWN2cG5rY3R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NjgyOTYsImV4cCI6MjA4NzM0NDI5Nn0.bJO5b3SCiSrX5yZPmJ2tdl5RCHVNv1z_kBgf8O_33c4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);